version: '2'

# Build the gridappsd docker containers
# Set the release environment variable in the shell
#   export GRIDAPPSD_TAG=rc2
# build the containers
#   docker-compose build

services:

  gridappsd_base:
    build: 
      context: .
      dockerfile: Dockerfile.gridappsd_base
    image: gridappsd/gridappsd_base:${GRIDAPPSD_TAG}

  gridappsd:
    build: 
      context: .
      dockerfile: Dockerfile.gridappsd
    image: gridappsd/gridappsd:${GRIDAPPSD_TAG}
    ports:
      - 61614:61614
      - 61616:61616
      - 61613:61613
    working_dir: /gridappsd
    environment:
      - PATH=/gridappsd/bin:/gridappsd/lib:/gridappsd/services/fncsgossbridge/service:$PATH
    volumes:
      - ./conf:/gridappsd/conf
      - ./applications:/gridappsd/applications
      - ./services:/gridappsd/services
#      - ./log:/tmp/gridappsd/log
#    depends_on:
#      - gridappsd/gridappsd_base
#
#    entrypoint: "tail -f /dev/null"

  viz:
    build:
      context: .
      dockerfile: Dockerfile.gridappsd_viz
    image: gridappsd/viz:${GRIDAPPSD_TAG}
    ports:
      - 8080:8082

    depends_on:
      - gridappsd

